### ISSUE TITLE
undefined method data_attributes for #<Intercom::Client

### ISSUE THREAD

**Issue by uhrohraggy** [intercom/intercom-ruby#542]
## Version info
  - intercom-ruby version: 3.9
  - Ruby version: ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-darwin18]

## Expected behavior
intercom.data_attributes should work per the README

## Actual behavior

Calling data_attributes on instance of Intercom::Client fails
```
Intercom::Client.new(token: '....')
intercom.data_attributes
Traceback (most recent call last):
        1: from (irb):4
NoMethodError (undefined method `data_attributes' for #<Intercom::Client:0x00007...
```
while `intercom.companies` and `intercom.contacts` returns returns instance of `Intercom::Service::Company` and `Intercom::Service::Contact`

**Comment by uhrohraggy** [comment]
Case of RTFM - works in intercom v4.1 Perhaps README could specify required versions for data_attributes?
