### PR TITLE
Add invalid document error handling

### PR DESCRIPTION
**Pull request by jonnyom**
#### Why?
We should be catching and handling this error more gracefully.

### CODE REVIEW

**Comment by sidonath** [comment]
We started getting `undefined method `[]' for nil:NilClass` at `lib/intercom/request.rb:114` after upgrading to 3.7.5 and it seems as this PR could be addressing 

However, it's hard to be certain as I have no idea what hides between `nil`, since line 113 is a little bit misleading, as it doesn't always raise in case of a failure:

```
raise_errors_on_failure(response) if parsed_body.nil?
```

Maybe `raise_errors_on_failure` should raise for every response with code `>= 400` or at least log the error somehow?

**Comment by jonnyom** [comment]
Hey @sidonath I think this PR wasn't actually added in 3.7.5, but rather 3.7.6

Sorry for the delay in getting back to you, this fell through the cracks.

**Comment by sidonath** [comment]
Hi @jonnyom! I've since realized that the issue was unrelated to these changes and opened https://github.com/intercom/intercom-ruby/issues/467
