### ISSUE TITLE
NoMethodError from intercom/request (again)

### ISSUE THREAD

**Issue by sidonath** [intercom/intercom-ruby#467]
## Version info
  - intercom-ruby version: 3.7.6
  - Ruby version: 2.5.3

## Expected behavior

`intercom-ruby` does not raise `NoMethodError`.

## Actual behavior

Same issue as in #339 that's still not fixed properly.

We started getting `undefined method '[]' for nil:NilClass` at [`lib/intercom/request.rb:114`](https://github.com/intercom/intercom-ruby/blob/7f9290049fa2af49d964fe5ada269712ed594d2e/lib/intercom/request.rb#L114) after upgrading from 3.5.25 to 3.7.5 and then to 3.7.6. But the problem is older than 3.5.25, so that's probably unrelated.

This exception was first fixed in #353, and then reverted/fixed in #359, by adding a handler for `nil`:

```ruby
raise_errors_on_failure(response) if parsed_body.nil?
raise_application_errors_on_failure(parsed_body, response.code.to_i) if parsed_body['type'] == 'error.list'
```

The problem, however, is that, contrary to the name, `raise_errors_on_failure` doesn't always raise: if it doesn't recognize the HTTP status code it doesn't do anything, so `nil` propagates to the next line.

Maybe `raise_errors_on_failure` should raise for every response with code `>= 400` or at least log the error somehow?

## Steps to reproduce

I'm not sure how to reproduce it. I don't know which response from Intercom triggers this exception, but the server responding with any unhandled status code without body would trigger the exception.

**Comment by theandrewykim** [comment]
@sidonath Hey there! Is there a specific request that you made that returned this error? That'd be really helpful in getting to the bottom of which response we're not accounting for here. Thanks!

**Comment by sidonath** [comment]
Hi @theandrewykim! Doesn't seem like there's something very specific, here's the breakdown:

* `events.create` - 1 occurrence
* `users.find` - 7 occurrences
* `users.save` - 2 occurrences

**Comment by theandrewykim** [comment]
@sidonath Thanks! Do you mind sharing your app_id with me? Maybe there is a specific error code being thrown that we're not accounting for shared between these three endpoints.

**Comment by sidonath** [comment]
@theandrewykim Sure, our ID is `f6jrsmcb`.

**Comment by theandrewykim** [comment]
@sidonath Sorry for leaving this one hanging! I thought I had gotten back to this. We didn't have access to the logs for the time frame you had written in about. Are you still running into issues with this?

**Comment by sidonath** [comment]
@theandrewykim Hi! We didn't get any new occurrences of this error for 3 months now.

Do you think it would still make sense to change `raise_errors_on_failure` to provide more details as originally suggested?

**Comment by sidonath** [comment]
@theandrewykim Hi there! We had the same exception again at 2019-07-01 08:54 pm EDT.

**Comment by kmossco** [comment]
We are currently having the same problem.

**Ruby 2.3.8**
**Intercom client 3.7.5**

```
Intercom::UnexpectedError: The error of type '' is not recognized. It occurred with the message: Server Error and http_code: '500'. Please contact Intercom with these details.
```

This happens on the following line in my code: `intercom.companies.save(ic_company)`. It seems to happen when your API is down, and as @sidonath mentioned this happens when the HTTP code fails to be recognised.

Reached out to support to understand if they could help, they mentioned the developers were informed, but just in case adding it here too. Let me know if there's anything I can help with.

**Comment by sidonath** [comment]
Should be resolved with #492.
